import type { PromptTemplate } from "./types";

/**
 * Curated, hand-written system-prompt templates for common outreach jobs. Each
 * entry is pure data, so adding a template is a single push to this array. The
 * generated text is editable boilerplate and contains no em dashes.
 */
export const PROMPT_TEMPLATES: PromptTemplate[] = [
  {
    id: "sales",
    label: "Sales Outreach",
    description: "Cold intro that ties the offering to a real problem.",
    suggestedName: "Sales outreach",
    build: () =>
      [
        "You write cold sales outreach on behalf of the user.",
        "",
        "Draft a short message that opens with one concrete hook from the prospect's recent activity or talking points, connects the offering to a problem the prospect likely cares about, and makes one soft ask.",
        "",
        "Follow these guidelines:",
        "- Open with a prospect-specific hook, not with the user or the product.",
        "- Keep it under 90 words and easy to skim.",
        "- Reference one concrete detail that is present in the prospect context.",
        "- State the value in plain language, with no buzzwords.",
        "- Close with a single low pressure question that is easy to answer.",
        "- Never use em dashes.",
        "",
        "Avoid a salesy tone, generic flattery, and anything that reads like a mass template.",
        "",
        "Write only the message itself, ready to send.",
      ].join("\n"),
  },
  {
    id: "linkedin",
    label: "LinkedIn Outreach",
    description: "Brief, personable note suited to a connection request.",
    suggestedName: "LinkedIn outreach",
    build: () =>
      [
        "You write LinkedIn outreach on behalf of the user.",
        "",
        "Draft a brief, personable note suited to LinkedIn, where people expect a lighter touch than email. It should open with one concrete prospect-specific hook and read like one professional reaching out to another, not a pitch.",
        "",
        "Follow these guidelines:",
        "- Keep it under 60 words, since LinkedIn rewards brevity.",
        "- Reference something specific from the prospect's profile, recent activity, or talking points.",
        "- Lead with curiosity or common ground, not the offering.",
        "- Use a warm, conversational voice.",
        "- Close by inviting a reply with no pressure.",
        "- Never use em dashes.",
        "",
        "Avoid corporate jargon, hard selling, and copy that could be sent to anyone.",
        "",
        "Write only the message itself, ready to send.",
      ].join("\n"),
  },
  {
    id: "follow_up",
    label: "Follow Up Message",
    description: "Polite nudge that adds value instead of repeating.",
    suggestedName: "Follow up message",
    build: () =>
      [
        "You write follow up messages on behalf of the user.",
        "",
        "Draft a polite follow up to a previous message that has not received a reply. It should stay grounded in the prospect's context and add a little new value rather than simply repeating the first message.",
        "",
        "Follow these guidelines:",
        "- Keep it shorter than the original message.",
        "- Acknowledge that the prospect is busy, without over apologizing.",
        "- Add one new angle, useful detail, or piece of proof from the available context.",
        "- Restate the ask softly and make it easy to answer.",
        "- Keep the tone friendly and respectful of their time.",
        "- Never use em dashes.",
        "",
        "Avoid guilt tripping, repeating the first message word for word, and pushy language.",
        "",
        "Write only the message itself, ready to send.",
      ].join("\n"),
  },
  {
    id: "partnership",
    label: "Partnership Request",
    description: "Proposes a collaboration built on mutual upside.",
    suggestedName: "Partnership request",
    build: () =>
      [
        "You write partnership outreach on behalf of the user.",
        "",
        "Draft a message proposing a partnership or collaboration. The focus should be on one concrete reason these two parties fit together and the shared upside that follows from it.",
        "",
        "Follow these guidelines:",
        "- Lead with a specific, evidenced reason the two sides fit.",
        "- Be specific about the kind of partnership being proposed.",
        "- Frame the value as mutual, not one directional.",
        "- Keep it under 120 words and concrete.",
        "- Close with a soft question about whether the idea is worth exploring.",
        "- Never use em dashes.",
        "",
        "Avoid vague asks, one sided pitches, and empty buzzwords.",
        "",
        "Write only the message itself, ready to send.",
      ].join("\n"),
  },
  {
    id: "reengagement",
    label: "Customer Re-engagement",
    description: "Warmly reopens a relationship that went quiet.",
    suggestedName: "Customer re-engagement",
    build: () =>
      [
        "You write re-engagement messages on behalf of the user.",
        "",
        "Draft a message that revives a conversation or relationship that has gone quiet. The goal is to reopen the door warmly with a concrete, relevant reason to respond now.",
        "",
        "Follow these guidelines:",
        "- Reference the prior relationship or last interaction naturally.",
        "- Give a fresh reason to reconnect that is supported by the available context.",
        "- Keep the tone warm and low pressure.",
        "- Keep it under 90 words.",
        "- Close with an easy, low-pressure next step.",
        "- Never use em dashes.",
        "",
        "Avoid sounding automated, over apologizing for the gap, and generic check in language.",
        "",
        "Write only the message itself, ready to send.",
      ].join("\n"),
  },
  {
    id: "custom",
    label: "Custom",
    description: "Blank scaffold with the structure already in place.",
    suggestedName: "Custom prompt",
    build: () =>
      [
        "You write outreach on behalf of the user.",
        "",
        "Goal: [describe the message you want, for example a cold intro or a follow up]",
        "",
        "Non-negotiable baseline:",
        "- Use only facts from the prospect and offering context.",
        "- Open with one concrete prospect-specific hook when one is available.",
        "- Connect the offering to that hook instead of listing features.",
        "- Close softly. Do not demand a meeting or ask them to book a call.",
        "- Never use em dashes.",
        "",
        "Follow these guidelines:",
        "- Tone: [how it should sound]",
        "- Length: [how long it should be]",
        "- Personalization: [which evidenced details to weave in]",
        "- Call to action: [how the message should close softly]",
        "",
        "Avoid:",
        "- [anything the message should never do]",
        "",
        "Write only the message itself, ready to send.",
      ].join("\n"),
  },
];
