"use client";

import { useEffect, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { Loader2, Sparkles } from "lucide-react";
import { toast } from "sonner";
import type { Prompt } from "@bespoke/db";
import { useCreatePrompt, useUpdatePrompt } from "@/lib/hooks/use-prompts";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Checkbox } from "@/components/ui/checkbox";
import { cn } from "@/lib/utils";
import { ConfirmDialog } from "@/components/shared/confirm-dialog";
import { InlineExplainer } from "@/components/shared/inline-explainer";
import { PromptBuilderPanel } from "./prompt-builder-panel";

interface PromptDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  /** When provided, the dialog edits this prompt; otherwise it creates one. */
  prompt?: Prompt;
}

/** A draft generated by the builder, held until an overwrite is confirmed. */
interface PendingDraft {
  content: string;
  suggestedName: string;
}

/**
 * Create / edit form for a prompt. Prompts are small, so they edit in a modal
 * rather than a detail route. The single-default rule is enforced server-side;
 * the checkbox only requests it.
 *
 * The Prompt Builder expands the modal to the right with a guided drafting
 * panel (templates + a structured form). It only ever produces an editable
 * draft: the editor stays the source of truth, and generated drafts are saved
 * exactly like hand-written prompts.
 */
export function PromptDialog({
  open,
  onOpenChange,
  prompt,
}: PromptDialogProps) {
  const isEdit = Boolean(prompt);
  const create = useCreatePrompt();
  const update = useUpdatePrompt(prompt?.id ?? "");
  const pending = create.isPending || update.isPending;

  const [name, setName] = useState("");
  const [systemPrompt, setSystemPrompt] = useState("");
  const [isDefault, setIsDefault] = useState(false);
  const [builderOpen, setBuilderOpen] = useState(false);
  const [pendingDraft, setPendingDraft] = useState<PendingDraft | null>(null);

  // Reset the form to the prompt (edit) or blank (create) each time it opens.
  useEffect(() => {
    if (!open) return;
    setName(prompt?.name ?? "");
    setSystemPrompt(prompt?.systemPrompt ?? "");
    setIsDefault(prompt?.isDefault ?? false);
    setBuilderOpen(false);
    setPendingDraft(null);
  }, [open, prompt]);

  /** Commits a generated draft into the editor and suggests a name if empty. */
  function commitDraft({ content, suggestedName }: PendingDraft) {
    setSystemPrompt(content);
    if (!name.trim() && suggestedName) setName(suggestedName);
    toast.success("Draft added to the editor. Edit it before saving.");
  }

  /**
   * Generated drafts overwrite the editor only after confirmation when the user
   * has already typed content, so nothing is lost silently.
   */
  function applyDraft(content: string, suggestedName: string) {
    const draft = { content, suggestedName };
    if (systemPrompt.trim()) setPendingDraft(draft);
    else commitDraft(draft);
  }

  function submit() {
    const input = {
      name: name.trim(),
      systemPrompt: systemPrompt.trim(),
      isDefault,
    };
    if (!input.name || !input.systemPrompt) return;
    const onSuccess = () => onOpenChange(false);
    if (isEdit) update.mutate(input, { onSuccess });
    else create.mutate(input, { onSuccess });
  }

  return (
    <>
      <Dialog open={open} onOpenChange={onOpenChange}>
        <DialogContent
          className={cn(
            "flex max-h-[92vh] flex-col overflow-y-auto transition-[max-width] duration-300 ease-[cubic-bezier(0.22,1,0.36,1)] motion-reduce:transition-none sm:h-[46rem]",
            builderOpen ? "sm:max-w-4xl lg:max-w-5xl" : "sm:max-w-lg",
          )}
        >
          <DialogHeader className="shrink-0">
            <DialogTitle>{isEdit ? "Edit prompt" : "New prompt"}</DialogTitle>
            <DialogDescription>
              Reusable instructions that customize tone, length, and angle while
              the baseline outreach rules stay in place.
            </DialogDescription>
          </DialogHeader>

          <div
            className={cn(
              "flex min-h-0 flex-1 flex-col gap-5",
              builderOpen && "md:flex-row md:gap-6",
            )}
          >
            {/* Editor column: the source of truth. */}
            <div className="flex min-h-0 min-w-0 flex-1 flex-col gap-4">
              <div className="flex shrink-0 flex-col gap-2">
                <Label htmlFor="prompt-name">Name</Label>
                <Input
                  id="prompt-name"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="Warm, concise opener"
                  autoFocus
                />
              </div>
              <div className="flex min-h-0 flex-1 flex-col gap-2">
                <div className="flex items-center justify-between">
                  <Label htmlFor="prompt-body">Prompt instructions</Label>
                  <InlineExplainer
                    topic="prompt"
                    staticCopy="The prompt is the set of instructions you give the AI before it writes a message. It controls how the AI thinks about your prospect and what kind of message it writes. Think of it as briefing a copywriter before they start writing: tone, length, angle, what to emphasize, what to avoid, how to open, and how to close."
                    getDraft={() => systemPrompt}
                  />
                </div>
                <Textarea
                  id="prompt-body"
                  value={systemPrompt}
                  onChange={(e) => setSystemPrompt(e.target.value)}
                  placeholder="Write in a warm, direct voice. Keep it under 90 words…"
                  className="min-h-[12rem] flex-1 resize-none"
                />
              </div>
              <label className="flex items-center gap-2 text-sm text-[var(--text-secondary)]">
                <Checkbox
                  checked={isDefault}
                  onCheckedChange={(v) => setIsDefault(v === true)}
                />
                Use as my default prompt
              </label>

              {!builderOpen ? (
                <Button
                  type="button"
                  variant="outline"
                  onClick={() => setBuilderOpen(true)}
                  className="w-full shrink-0"
                >
                  <Sparkles className="h-4 w-4 text-[var(--accent-text)]" />
                  Prompt Builder
                </Button>
              ) : null}
            </div>

            {/* Builder column: expands from the right, collapsible. */}
            <AnimatePresence>
              {builderOpen ? (
                <motion.div
                  key="builder"
                  initial={{ opacity: 0, x: 12 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 12 }}
                  transition={{ duration: 0.2, ease: [0.22, 1, 0.36, 1] }}
                  className="flex min-h-0 w-full flex-col border-t border-[var(--border-default)] pt-5 md:h-full md:w-96 md:border-t-0 md:border-l md:pt-0 md:pl-6 lg:w-[30rem]"
                >
                  <PromptBuilderPanel
                    onApply={applyDraft}
                    onClose={() => setBuilderOpen(false)}
                  />
                </motion.div>
              ) : null}
            </AnimatePresence>
          </div>

          <DialogFooter className="shrink-0">
            <Button
              variant="outline"
              onClick={() => onOpenChange(false)}
              disabled={pending}
            >
              Cancel
            </Button>
            <Button
              onClick={submit}
              disabled={pending || !name.trim() || !systemPrompt.trim()}
            >
              {pending ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
              {isEdit ? "Save" : "Create"}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <ConfirmDialog
        open={pendingDraft !== null}
        onOpenChange={(o) => {
          if (!o) setPendingDraft(null);
        }}
        title="Replace prompt content?"
        description="This replaces what you have typed in the editor with the generated draft. You can still edit it afterwards."
        confirmLabel="Replace"
        destructive={false}
        onConfirm={() => {
          if (pendingDraft) commitDraft(pendingDraft);
          setPendingDraft(null);
        }}
      />
    </>
  );
}
